### ISSUE TITLE
Error: unexpected server response (302)

### ISSUE THREAD

**Issue by D-Nice** [streamr-dev/streamr-client#10]
The following code fails with the above error on my personal machines and even in cloud IDEs. I also supplemented the subscription options with an apiKey for the authKey parameter, and same issue persists. Also, your own node example file fails, as it doesn't import ws.

```js
var StreamrClient = require('streamr-client')
global.WebSocket = require('ws')

// Create the client with default options
var client = new StreamrClient()

// Subscribe to a stream
var subscription = client.subscribe(
	{
		stream: 'QW1-CxxyRtqp45Bvrd9iwg',
		// Resend the last 10 messages on connect
		resend_last: 10
	},
    function(message) {
    	// Handle the messages in this stream
		console.log(message)
    }
)
```

**Comment by harbu** [comment]
Hi!

The newest NPM package version isn't yet compatible with our production systems. However, we will be updating them very soon.

In the meantime, I'd advise using version 0.8.1 of this package `npm install streamr-client@0.8.1`. The syntax is a bit different in this version. The following snippet should work for you:

```js
var StreamrClient = require('streamr-client')
global.WebSocket = require('ws')

var client = new StreamrClient()

var subscription = client.subscribe(
  'QW1-CxxyRtqp45Bvrd9iwg',
  function(message, streamId, timestamp, counter) {
    console.log(message)
  },
  {
    resend_last: 10
  }
)

```

The documentation for version 0.8.1: https://github.com/streamr-dev/streamr-client/blob/033cc73f4f09b47685be2438d79c3041d1c8fe66/README.md

Thanks for letting us know about these problems and sorry for the inconvenience caused. We will also be fixing the documentation to reflect the missing ws import.

**Comment by D-Nice** [comment]
Thanks, I'll try the older version!

**Comment by hpihkala** [comment]
Production has been updated to match the new streamr-client. Closing this issue.
